# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: image.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'image.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bimage.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"?\n\x0bPlotRequest\x12%\n\x01x\x18\x01 \x03(\x0b\x32\x1a.google.protobuf.Timestamp\x12\t\n\x01y\x18\x02 \x03(\x01\"\x1d\n\x0cPlotResponse\x12\r\n\x05image\x18\x01 \x01(\x0c\x32:\n\x0bPlotService\x12+\n\x0cGeneratePlot\x12\x0c.PlotRequest\x1a\r.PlotResponseB\x0c\n\x08protoOutP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\010protoOutP\001'
  _globals['_PLOTREQUEST']._serialized_start=48
  _globals['_PLOTREQUEST']._serialized_end=111
  _globals['_PLOTRESPONSE']._serialized_start=113
  _globals['_PLOTRESPONSE']._serialized_end=142
  _globals['_PLOTSERVICE']._serialized_start=144
  _globals['_PLOTSERVICE']._serialized_end=202
# @@protoc_insertion_point(module_scope)
